### ISSUE TITLE
Remove "Open" option at end of initializr wizard

### ISSUE THREAD

**Issue by dsyer** [eduk8s-labs/lab-spring-boot-k8s-getting-started#3]
The Initializr extension in the IDE offers two options at the end: "Open" and "Add to Workspace". The "Open" button opens a new workspace, which is a new tab in code-server, and takes you out of the eduk8s lab. Ideally we'd like to simply disable that button. An alternative would be to fix code-server so it doesn't open a new tab, but they have shown themselves to be against that option in the upstream issue tracker.

**Comment by martinlippert** [comment]
We could fork the existing VSCode extension for Spring Initializr, remove the "Open" button, and install our custom extension in the workshop instead of the standard one.

If we remove the "Open" button, the remaining "Add to workspace" button would be the only option left and could therefore be removed, too. Instead, it should be added to the workspace automatically.

**Comment by BoykoAlex** [comment]
I agree with @martinlippert - I'd remove the popup asking to open a new workspace or add to existing. I'd add a boolean setting "add project to current workspace". This setting could be set to `true` when assembling the Docker image. Should be trivial to do this...
Think chances are high original VSCode extension would accept it.

**Comment by dsyer** [comment]
This is working now. I suppose we could push the change to the shared docker images instead of only using it here.
