### ISSUE TITLE
Modify/fork Initializr extension in IDE so we can add features

### ISSUE THREAD

**Issue by dsyer** [eduk8s-labs/lab-spring-boot-k8s-getting-started#4]
...maybe even turn it into proper checkboxes?

**Comment by martinlippert** [comment]
The general idea of forking the initializr integration for VSCode makes sense as a next step. In the longer run, we could think about owning that extension ourselves and moving that forward at a broader scope, maybe including those UI/UX changes like checkboxes, etc.

**Comment by BoykoAlex** [comment]
@dsyer The forked VSCode initializr extension is added in the branch **vscode-initializr-fork**. The initializr extension from the fork has the fix for #3 It'd be great if you could try it out :-)
If it looks good, I'll look into properly integrating the forked initializr extension into https://github.com/eduk8s/pkgs-java-tools probably

**Comment by dsyer** [comment]
How do I try it out if it's in a branch? If you put it on master it will show up in the lab right?

**Comment by BoykoAlex** [comment]
I've been testing it with our own instance of eduk8s... I can fold it in master and then we shall see if it shows up automatically...

**Comment by BoykoAlex** [comment]
It's in master now
