### ISSUE TITLE
Cannot paste into YAML array element

### ISSUE THREAD

**Issue by dsyer** [eduk8s-labs/lab-spring-boot-k8s-getting-started#9]
Tried this:

```html
<pre class="pastable" data-file="/home/eduk8s/exercises/demo/deployment.yaml" data-yaml-path="spec.template.spec.containers[0]">
...
</pre>
```

But it didn't do anything. I need to select the element (by index or name or something).

**Comment by kdvolder** [comment]
Right... navigation into array was left as a todo. I guess its time to take care of that one. Luckily I don't think its very hard. I should be able to get that working today.

**Comment by kdvolder** [comment]
New version of vscode-helper now supports using `[<index>]` notation in yaml path.

I've added it to this workshop. See: https://github.com/eduk8s-tests/lab-spring-boot-k8s-getting-started/commit/1f2945d34a7e7a230ad9856384b825928fc88b51

**Comment by kdvolder** [comment]
@dsyer  I should also mention that this new version also decides 'where to paste' based on yamlpath a little differently than before. 

Before the paste snippet would be pasted at the beginning of the node being pointed. I changed this to be the end instead. 

Two reasons for this:

First, it seems somewhat more logical to add new content at the end rather than the beginning

Second it offended my sense of 'estethics' to produce something like this:

```
containers:
- new: added
  stuff: here
  name:foo
```

I.e new stuff added in front of the `name: foo` of a sequence of container definitions.
Technically I suppose it doesn't matter but it looks weird to me.

**Comment by dsyer** [comment]
I think that's working. Thanks.
